### ISSUE TITLE
SQL Injection and Cross-site Scripting in class-validator

### ISSUE THREAD

**Issue by ElSeniorMikael** [whoami-shubham/obfuscator-io-metro-plugin#16]
Hello, i am updating one of my project and i've seen an error coming from this libraries.

Obfuscator-io-metro-plugin depend on javascript-obfuscator and it seems that there is a critical error on this libraries as the name of the issue say, it would be an SQL injection and cross-site scripting in class-validator. I was wondering it there was any plan on patching it or update the libraries so it get the fix (if there's one)

<img width="819" alt="Screenshot 2023-01-30 at 10 59 22 AM" src="https://user-images.githubusercontent.com/73765089/215528012-d7a63995-3f7c-4194-ae5f-c739d3f94a92.png">

**Comment by whoami-shubham** [comment]
Thanks for creating this issue. fixed it in PR #18
