### ISSUE TITLE
Check whether this library works for iOS apps

### ISSUE THREAD

**Issue by whoami-shubham** [whoami-shubham/obfuscator-io-metro-plugin#2]
It works for android apps. Just wanted to confirm whether it works for iOS apps. 
**steps to test.**
- use this library in your react native app code
- create `.ipa` file (or any other file which is equivalent of `apk` file in android)
- decompile  `.ipa` file to extract the `.ios.bundle` file 
- check if `.ios.bundle` file content is obfuscated or not, if content is obfuscated it works.

**Comment by andresarezo** [comment]
Hi, 

You wanted to let you know this warning when make an archive in xcode:

warning:  Obfuscation SKIPPED [Not a *bundle* command]

Regards

**Comment by whoami-shubham** [comment]
@andresarezo  Thanks for checking this. Could you please tell me what was the options that you passed.

**Comment by andresarezo** [comment]
Hi,

I figure out that if I change in xcode -> build Pahses and change ram-bundle to bundle under "Bundle React Native code.."

The warning still showing but the main.jsbundle it's obfuscated!!!

**Comment by andresarezo** [comment]
Im passing this config:

const jsoMetroPlugin = require('obfuscator-io-metro-plugin')(
  {
    compact: false,
    sourceMap: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    numbersToExpressions: true,
    simplify: true,
    shuffleStringArray: true,
    splitStrings: true,
    stringArrayThreshold: 1,
  },
  {
    runInDev: true,
    logObfuscatedFiles: true /* generated files will be located at ./.jso */,
  }
);

**Comment by whoami-shubham** [comment]
Yes. Thanks I will add this in readme file.

**Comment by houmie** [comment]
@whoami-shubham I would love to verify if this works for iOS. How did you decompile .ipa file to extract the .ios.bundle file, please?

@andresarezo May you please elaborate a bit more on your findings? Under build-phases of a react-Native iOS project, I can't see "Bundle React Native code". 

And where do you paste this code?
```
const jsoMetroPlugin = require('obfuscator-io-metro-plugin')(
{
compact: false,
sourceMap: true,
controlFlowFlattening: true,
controlFlowFlatteningThreshold: 1,
numbersToExpressions: true,
simplify: true,
shuffleStringArray: true,
splitStrings: true,
stringArrayThreshold: 1,
},
{
runInDev: true,
logObfuscatedFiles: true /* generated files will be located at ./.jso */,
}
);
```

Thanks

**Comment by aamir-ds** [comment]
Its still not fixed @whoami-shubham

**Comment by aamir-ds** [comment]
it is generating .jso folder with obfuscated code in it but after creating .ipa file its not showing obfuscated code in main.jsbundle file. Do I need to make some changes in Build phases Bundle React native code & images?

I am passing this config:
const jsoMetroPlugin = require("obfuscator-io-metro-plugin")(
  {
    compact: true,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: 0,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    numbersToExpressions: false,
    renameGlobals: false,
    selfDefending: false,
    simplify: true,
    splitStrings: false,
    stringArray: true,
    stringArrayCallsTransform: false,
    stringArrayCallsTransformThreshold: 0.5,
    stringArrayEncoding: [],
    stringArrayIndexShift: true,
    stringArrayRotate: true,
    stringArrayShuffle: true,
    stringArrayWrappersCount: 1,
    stringArrayWrappersChainedCalls: true,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: 'variable',
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false
  },
  {
    runInDev: true /* optional */,
    logObfuscatedFiles: true /* optional generated files will be located at ./.jso */,
  }
);

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
  ...jsoMetroPlugin,
};

**Comment by MCervenka** [comment]
It is not working for ios. I have React-native 0.81.4
I have runInDev: true option selected, but the archived ipa file still have main.jsbundle not obfuscated

**Comment by MCervenka** [comment]
Added some logging. It seems that it cannot find any files to obfuscate. 
Maybe I would create a PR for this if I would be able to fix it
