### ISSUE TITLE
License for the plugin code

### ISSUE THREAD

**Issue by satheeshwaran** [whoami-shubham/obfuscator-io-metro-plugin#3]
Good work on the plugin.

It would be really great if you could add a Licence to the project so that people can pick it up with confidence. Since the code is already open-sourced and if you don't have intentions to restrict the usage I would recommend an MIT license for the same.

The original Javascript Obfuscator is BSD licensed.

**Comment by whoami-shubham** [comment]
@satheeshwaran thanks for pointing it out. I have provided value `"license": "MIT",` in package.json already do I need to add something else?
