### ISSUE TITLE
Need usefull sourcemaps to debug production code

### ISSUE THREAD

**Issue by mateosilguero** [whoami-shubham/obfuscator-io-metro-plugin#7]
Currently, generated sourcemaps are not usefull to upload to (for example), Sentry o another platform.

`Metro is generating source maps that won't be useful after obfuscation.`

**Comment by whoami-shubham** [comment]
generated sourcemap is not useful right now, I will need some help to figure out this.

**Comment by whoami-shubham** [comment]
I don't think obfuscated/deobfuscated source map will be useful in production since the code is obfuscated so it will generate errors that will have obfuscated variable names. you might have to use some sort of custom error reporting to identify the entry point of error.

**Comment by KelvinPortuphy** [comment]
any update here?
